---
frontend:
  name: frontend-application
  port: 8081

backend:
  name: backend-spring-service
  port: 8080


url: https://{{ tpl $.Values.host $ }}
host: {{ $.Values.global.appname }}-{{ $.Release.Namespace }}.{{ $.Values.global.cluster.baseDomain }}
oidcIssuerUrl: https://keycloak-{{ $.Release.Namespace }}.{{ $.Values.global.cluster.baseDomain }}/auth/realms/consultant360

#Required Values:
global:
  labels: []
  appname: example-application
  cluster:
    baseDomain: REQUIRED_GLOBAL_VARIBLE