---
enabled: true

url: "https://{{ tpl $.Values.host $ }}"
host: "{{ $.Values.global.appname }}-{{ $.Release.Namespace }}.{{ $.Values.global.cluster.baseDomain }}"
oidcIssuerUrl: "https://keycloak-{{ $.Release.Namespace }}.{{ $.Values.global.cluster.baseDomain }}/auth/realms/{{ $.Release.Name }}"

#Required Values
global:
  frontend:
    name: frontend-application
    port: 8081
  backend:
    name: backend-spring-service
    port: 8080
  labels: []
  appname: oauth
  cluster:
    baseDomain: REQUIRED_GLOBAL_VARIBLE
