{{- with $.Values }}
{{- if .enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $.Values.global.appname }}
  labels:
    app: {{ $.Values.global.appname }}
    name: oauth2-proxy
    {{- range $label := $.Values.global.labels }}
    {{ $label.key }} : {{ tpl $label.value $ }}
    {{- end}}
spec:
  host: {{ tpl .host $ }}
  port:
    targetPort: '8080'
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: oauth2-proxy
  wildcardPolicy: None
{{- end -}}
{{- end -}}