{{- with $.Values }}
{{- if .enabled }}
kind: Service
apiVersion: v1
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: oauth2proxy
  labels:
    app: {{ $.Values.global.appname }}
    name: oauth2-proxy
    {{- range $label := $.Values.global.labels }}
    {{ $label.key }} : {{ tpl $label.value $ }}
    {{- end}}
  name: oauth2-proxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: oauth2-proxy
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
status:
  loadBalancer: {}
{{- end -}}
{{- end -}}